package com.project.framework.model;
// Generated 29-ene-2017 15:21:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aplicacion generated by hbm2java
 */
public class Aplicacion  implements java.io.Serializable {


     private int id;
     private String texto;
     private String descripcion;
     private Set controls = new HashSet(0);

    public Aplicacion() {
    }

	
    public Aplicacion(int id, String texto) {
        this.id = id;
        this.texto = texto;
    }
    public Aplicacion(int id, String texto, String descripcion, Set controls) {
       this.id = id;
       this.texto = texto;
       this.descripcion = descripcion;
       this.controls = controls;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getControls() {
        return this.controls;
    }
    
    public void setControls(Set controls) {
        this.controls = controls;
    }




}


