package com.project.framework.model;
// Generated 10-jun-2017 20:17:35 by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Continente generated by hbm2java
 */
@Entity
@Table(
    name="continente",
    schema="public"
)
public class Continente  implements Serializable {


     private int id;
     private String texto;

    public Continente() {
    }

	
    public Continente(int id) {
        this.id = id;
    }
    public Continente(int id, String texto) {
       this.id = id;
       this.texto = texto;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="texto")
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }




}


