package com.project.framework.model;
// Generated 10-jun-2017 20:17:35 by Hibernate Tools 4.3.1


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Continente generated by hbm2java
 */
//@Table(name = "continente", schema = "public")
@Entity
@Table(name = "continente")
public class Continente  implements Serializable {

    public Continente() {}
	
    public Continente(int id) {
        this.id = id;
    }
    
    public Continente(int id, String texto) {
       this.id = id;
       this.texto = texto;
    }

//    @Column(name = "id", unique = true, nullable = false)
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(name = "texto")
    private String texto;
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
}


