package com.project.framework.model;
// Generated 10-jun-2017 20:17:35 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name="cuenta"
    ,schema="public"
)
public class Cuenta  implements java.io.Serializable {


     private int id;
     private int usuario;
     private String email;
     private String contrasena;
     private int preguntaSeguridad;
     private String respuestaSeguridad;
     private String seudonimo;

    public Cuenta() {
    }

    public Cuenta(int id, int usuario, String email, String contrasena, int preguntaSeguridad, String respuestaSeguridad, String seudonimo) {
       this.id = id;
       this.usuario = usuario;
       this.email = email;
       this.contrasena = contrasena;
       this.preguntaSeguridad = preguntaSeguridad;
       this.respuestaSeguridad = respuestaSeguridad;
       this.seudonimo = seudonimo;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="usuario", nullable=false)
    public int getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(int usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="contrasena", nullable=false)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    
    @Column(name="pregunta_seguridad", nullable=false)
    public int getPreguntaSeguridad() {
        return this.preguntaSeguridad;
    }
    
    public void setPreguntaSeguridad(int preguntaSeguridad) {
        this.preguntaSeguridad = preguntaSeguridad;
    }

    
    @Column(name="respuesta_seguridad", nullable=false)
    public String getRespuestaSeguridad() {
        return this.respuestaSeguridad;
    }
    
    public void setRespuestaSeguridad(String respuestaSeguridad) {
        this.respuestaSeguridad = respuestaSeguridad;
    }

    
    @Column(name="seudonimo", nullable=false)
    public String getSeudonimo() {
        return this.seudonimo;
    }
    
    public void setSeudonimo(String seudonimo) {
        this.seudonimo = seudonimo;
    }




}


