package com.project.framework.model;
// Generated 29-ene-2017 15:21:22 by Hibernate Tools 4.3.1



/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private int id;
     private PreguntaSeguridad preguntaSeguridad;
     private Usuario usuario;
     private String email;
     private String contrasena;
     private String respuestaSeguridad;
     private String seudonimo;

    public Cuenta() {
    }

    public Cuenta(int id, PreguntaSeguridad preguntaSeguridad, Usuario usuario, String email, String contrasena, String respuestaSeguridad, String seudonimo) {
       this.id = id;
       this.preguntaSeguridad = preguntaSeguridad;
       this.usuario = usuario;
       this.email = email;
       this.contrasena = contrasena;
       this.respuestaSeguridad = respuestaSeguridad;
       this.seudonimo = seudonimo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public PreguntaSeguridad getPreguntaSeguridad() {
        return this.preguntaSeguridad;
    }
    
    public void setPreguntaSeguridad(PreguntaSeguridad preguntaSeguridad) {
        this.preguntaSeguridad = preguntaSeguridad;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getRespuestaSeguridad() {
        return this.respuestaSeguridad;
    }
    
    public void setRespuestaSeguridad(String respuestaSeguridad) {
        this.respuestaSeguridad = respuestaSeguridad;
    }
    public String getSeudonimo() {
        return this.seudonimo;
    }
    
    public void setSeudonimo(String seudonimo) {
        this.seudonimo = seudonimo;
    }




}


