package com.project.framework.model;
// Generated 29-ene-2017 15:21:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * PreguntaSeguridad generated by hbm2java
 */
public class PreguntaSeguridad  implements java.io.Serializable {


     private int id;
     private String texto;
     private Set cuentas = new HashSet(0);

    public PreguntaSeguridad() {
    }

	
    public PreguntaSeguridad(int id, String texto) {
        this.id = id;
        this.texto = texto;
    }
    public PreguntaSeguridad(int id, String texto, Set cuentas) {
       this.id = id;
       this.texto = texto;
       this.cuentas = cuentas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


